version: "3.9"

# docker-compose exec cassandra cqlsh
services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"